# Login
USERNAME = "abhishekcreations"
PASSWORD = "ac2006"

# Search providers — Bing first (RECOMMENDED)
BING_API_KEY = "0de410772e521468709883f460fd8e4c9da7e29fda2e7133a98b0663def3356d"

# Optional Google CSE (will be tried AFTER Bing; may 429 if over daily cap)
GOOGLE_API_KEY = "AIzaSyBOKdDa8bRYLsBKvEfJlR7fn6v25OzjWzc"
GOOGLE_CX      = "d4816afb144cb4f3b"

# Optional SerpAPI (additional fallback)
# SERPAPI_KEY = "..."

# Optional Postgres DB (otherwise SQLite is used automatically)
# DATABASE_URL = "postgresql+psycopg2://USER:PASSWORD@HOST:5432/DBNAME"
