# Authentication
USERNAME = "abhishekcreations"
PASSWORD = "ac2006"

# Database (optional, SQLite is default)
# DATABASE_URL = "postgresql+psycopg2://user:pass@host:5432/dbname"

# Google CSE (replace with your own values)
GOOGLE_API_KEY = "AIzaSyBCa8hijfM8N29khu4ME812dgu4MdMpGH0"
GOOGLE_CX = "74e4c5671b1364c22"

# Bing via Azure AI Services
BING_API_KEY = "3By45PyDF0aQb6ftIAVfGZENduDEZddEn7yGFLgfX8NseaJmx240JQQJ99BIACYeBjFXJ3w3AAAEACOGJG2p"
BING_ENDPOINT = "https://ac-scraper-ai.cognitiveservices.azure.com"
