USERNAME = "abhishekcreations"
PASSWORD = "ac2006"

# Database (optional, SQLite is default)
# DATABASE_URL = "postgresql+psycopg2://user:pass@host:5432/dbname"

# Google CSE (quota 100/day – may already be exhausted)
GOOGLE_API_KEY = "AIzaSyBOKdDa8bRYLsBKvEfJlR7fn6v25OzjWzc"
GOOGLE_CX = "d4816afb144cb4f3b"

# Bing via Azure AI Services
BING_API_KEY = "3By45PyDF0aQb6ftIAVfGZENduDEZddEn7yGFLgfX8NseaJmx240JQQJ99BIACYeBjFXJ3w3AAAEACOGJG2p"
BING_ENDPOINT = "https://ac-scraper-ai.cognitiveservices.azure.com"

# Optional fallback providers
# SERPAPI_KEY = "..."
# SCRAPINGBEE_API_KEY = "..."
# BROWSERLESS_API_KEY = "..."
